project:
  type: website
  output-dir: docs
  
website:
  title: "Digital training for building resilience:"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Study Examples
        menu:
          - text: A therapist-guided smartphone app for major depression in young adults
            href: study1.qmd
          - text: Study 2
            href: study2.qmd
          - text: Effects of cyclic adjustment training delivered via a mobile device on psychological resilience, depression, and anxiety in Chinese post-surgical breast cancer patients
            href: study3.qmd
    tools:
      - icon: twitter
        href: https://digilab.uni-graz.at/en/
      - icon: github
        href: https://github.com/FloPaho/building-resilience
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: minty
    toc: true

editor: source


