project:
  type: website
  output-dir: docs
  
website:
  title: "Digital training for building resilience:"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Study Examples
        menu:
          - text: Study 1
            href: study1.qmd
          - text: Study 2
            href: study2.qmd
          - text: Study 3
            href: study3.qmd
    tools:
      - icon: twitter
        href: https://digilab.uni-graz.at/en/
      - icon: github
        href: https://github.com/FloPaho/building-resilience
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: minty
    toc: true

editor: source


