---
title: "The comparative effect of internet-based cognitive behavioral counseling versus face to face cognitive behavioral counseling in terms of student's resilience"
subtitle: "A randomized controlled trial"
---

# What is this study about?

Stress is leading factor regarding the development of mental health issues, such as anxiety disorders and depression. Improving one's ability to overcome or bounce back from adversities therefore represents an a crucial way of maintaining or recovering to mental health. This ability is termed **resilience**. 

The current study investigates whether resilience training shows short-term as well as long-term improvements. Secondly, the authors compare internet-based and face-to-face resilience-training in terms of efficacy. Additionally, both are compared to a control group consisting of individuals waiting for treatment. 90 pupils with a mean age of 12 participated in the study, i.e., 30 in each group.  

# What does this study find?

The internet-based and the face to face resilience training showed [no significant difference]{title="Mean difference=0.17, p>.05" style="font-weight: bold; color: #78c2ad;"}. Both, however, elicited a self-reported [increase in resilience]{title="F=545.501, p<0.001" style="font-weight: bold; color: #78c2ad;"}. Further, both training variants [differed significantly]{title="F=37168.533, p<.001" style="font-weight: bold; color: #78c2ad;"} from the control group after the training, but were equal before. We can therefore conclude that training was successful in both training groups. Even five weeks after the end of the training phase, differences between both training groups and the control group were still significant. 

However, we should be careful with interpreting these findings, as the study not only illustrates a comparatively huge effect size, but also has some weaknesses. In general, many important things were not reported, such as the individual resilience values, whether the participants were aware of the other groups etc. These things can have implications on the analyses, which is why caution is advised when it comes to interpret these findings.

# References

Kadek Suranata, Itsar Bolo Rangka & Agus Aan Jiwa Permana | (2020)
 The comparative effect of internet-based cognitive behavioral counseling versus face to
 face cognitive behavioral counseling in terms of student’s resilience, Cogent Psychology, 7:1,
 1751022, DOI: 10.1080/23311908.2020.175102

[Download article](https://www.tandfonline.com/doi/full/10.1080/23311908.2020.1751022)