---
title: "Digital training for building resilience:"
subtitle: "Systematic review, meta‐analysis, and meta‐regression"
---

# Nützliches:

hier ist ein Link für die Nutzung von Quarto: [Quarto Tutorial vom R Kurs von Brunner](https://r-23w-12.netlify.app/)

## Tooltip (Hier ist ein Beispiel wie ihr ein tooltip machen könnt)

Here is some text with a tooltip: [hover over me]{title="This is the tooltip text." style="font-style: italic;"}.

# Overview

Resilience is learnable and broadly described as an individual's adaptive coping
ability, its potential value for stress reduction must be explored. With a global
coronavirus pandemic, innovative ways to deliver resilience training amidst
heightened mental health concerns must be urgently examined. This systematic
review aimed to (1) evaluate the effectiveness of digital training for building resilience
and reducing anxiety, depressive and stress symptoms and (2) to identify
essential features for designing future digital training. A three‐step search was
conducted in eight electronic databases, trial registries and grey literature to locate
eligible studies. Randomised controlled trials examining the effects of digital
training aimed at enhancing resilience were included. Data analysis was conducted
using the Stata version 17. Twenty‐two randomised controlled trials involving 2876
participants were included. Meta‐analysis revealed that digital training significantly
enhanced the participants' resilience with moderate to large effect (g = 0.54–1.09)
at post‐intervention and follow‐up. Subgroup analyses suggested that training
delivered via the Internet with a flexible programme schedule was more effective
than its counterparts. This review supports the use of digital training in improving
resilience. Further high‐quality randomised controlled trials with large sample size
are needed.

# What is this study about?

Stress is an inherent part of everyday life (Schwarzer & Luszczynska,
2013) and having chronic stress can lead to deleterious impacts
on one's health and well‐being (Bliese et al., 2017; García‐León
et al., 2019). Theoretically, stress may be understood from two approaches,
systemic or psychological stress. The systemic stress
approach based on the general adaptation syndrome (Selye, 1965),
defines stress as a state brought upon by changes in the physiological
systems. On the other hand, the transactional model of stress
(Lazarus & Folkman, 1984) adopts a psychological stance and describes
how stress arises when individuals perceive that they are
unable to adequately cope with the situation or are experiencing
threats to their well‐being. While different in their approaches, both

# What does this study find?

The search results are shown in Figure 2. A total of 28,816 records
were identified from eight electronic databases and 6 records were
retrieved from Google Scholar. After 5490 duplicates were removed,
1392 records were screened by their title and abstract based on the
eligibility criteria. One hundrend six articles were screened in full text,
and 84 articles were further excluded. Finally, 22 randomised
controlled trials were included in this review, 21 were published papers
(Aiken et al., 2014; Anderson et al., 2017; Barry et al., 2019; Bekki
et al., 2013; Brog et al., 2022; Ebert et al., 2021; Flett et al., 2019, 2020;
Harrer et al., 2018; Heckendorf et al., 2019; Hoorelbeke et al., 2015;
Litvin et al., 2020; Morrison et al., 2017; Park et al., 2020; Raevuori
et al., 2021; Roig et al., 2020; Shaygan et al., 2021; Suranata
et al., 2020; Zhou et al., 2019) and 1 unpublished doctoral dissertation
(Baqai, 2020). The reviewer agreement on the selection of eligible
studies was good (k = 0.74). Two studies (Joyce et al., 2019; Smyth
et al., 2018) did not provide sufficient information in their publication
and were excluded from the meta‐analysis.

# How does the Digital Psychology Lab teaching evaluate this study?

However, this review is limited for several reasons. Given that
eligible articles that are not published in the English Language were
omitted, this has potentially led to publication bias. High heterogeneity
was also detected, which was not unexpected because the
eligible trials showed variation in the population (e.g., healthy, or
diseased individuals) and their intervention contents. Additionally,
the included trials had relatively small sample sizes that could
potentially lead to an overestimation of the effect sizes. The use of
subjective measures for outcomes may be limited by social desirability
biases and expectancy effects. Finally, the GRADE evidence
suggests low to very low confidence in the findings.

# Conclusion for teaching practice

This review applied a rigorous and systematic approach to examine
the effectiveness of digital resilience training by conducting the
meta‐analysis and meta‐regression of randomised controlled trials.
With respect to its limitations of high heterogeneity and publication
bias, the findings lay the foundation for future work. Nonetheless,
this review supports the use of digital resilience training from a
strength‐based and preventive angle. Digital resilience training
delivered over the Internet with a flexible training programme was
found to exert a greater positive influence on psychological wellbeing
such as resilience while reducing anxiety and depressive
symptoms. Future trials are needed to examine the effects of digital
training platforms on resilience. Large‐scale randomised controlled
trials that are prospectively registered and adopting intention‐totreat
analysis must be performed to ascertain the effectiveness of
digital resilience training.

# Study example

Wei How Darryl Ang: Data curation, formal analysis, investigation,
writing – original draft, writing – review and editing and visualization.
Han Shi Jocelyn Chew: Data curation, formal analysis, writing – original
draft and writing – review and editing. Jie Dong: Writing – original
draft and writing – review and editing. Huso Yi: Writing – original draft
and writing – review and editing. Rathi Mahendren: Writing – original
draft and writing – review and editing. Ying Lau: Conceptualization,
methodology, design, validation, formal analysis, investigation,
resources, data curation, writing – original draft, writing – review and
editing, visualization and supervision.

# References

Abdulai, A.‐F., Tiffere, A.‐H., Adam, F., & Kabanunye, M. M. (2021).
COVID‐19 information‐related digital literacy among online health
consumers in a low‐income country. International Journal of Medical
Informatics, 145, 104322. https://doi.org/10.1016/j.ijmedinf.2020.
10432