---
title: "A therapist-guided smartphone app for major depression in young adults:"
subtitle: "A randomized clinical trial"
editor: 
  markdown: 
    wrap: 72
---

# What is this study about?

Depression is a big issue in many peoples life and the availability of
mental health care is still insufficient. For this reason digitally
delivered mental health care could help providing psychological support
on a greater scale. One way to deliver mental health care is via a
smartphone app. One such app would be the **Meru Health Program (MHP)**,
which consists of elements from three evidence-based interventions for
depression. This elements are behavioral activation, mindfulness, and
cognitive-behavioral therapy (CBT). The app includes support by a
licensed remote therapist; text, videos, audio-guided mindfulness
meditation exercises, infographics illustrating CBT principles, and
journal prompts.

This study examined the effect of an 8-week intervention study, where
they compared the effect of MHP on major depression compared to a
control group. Therefore, young finish adults with a diagnosis of major
depression either continued their treatment as usual (control group) or
did additionally the MHP intervention. Depressive symptops, anxiety
symptoms, sleep problems, perceived stress, quality of life, resilience,
mindfulness and attrition were assessed at the beginning of the
intervention, the middle of the intervention (after 4 weeks), the end of
the intervention (after 8 weeks), 3 months after the intervention and 6
months after the intervention.

# What does this study find?

The control group and the MHP intervention group did not differ in their
depression symptoms throughout the end of the intervention and
follow-ups.

Patients on antidepressants showed significantly greater [reduction in
depression]{title="d=-0.73, p=0.01"
style="font-weight: bold; color: #78c2ad;"} after 6 months the MHP
intervention group versus the control group. Patients not on
antidepressants showed no between-group differences.

But an increase in [**resilience**]{title="d=0.32,p=0.03"
style="font-weight: bold; color: #78c2ad;"} and
[mindfulness]{title="d=0.57, p=0.002"
style="font-weight: bold; color: #78c2ad;"} and a reduction in
[perceived stress]{title="d=-0.52, p=0.008"
style="font-weight: bold; color: #78c2ad;"} has been found in the MHP
intervention group compared to the control group. There were no
differences found in anxiety, sleep disturbances, and quality of life
between the groups.

# References

Raevuori, A., Vahlberg, T., Korhonen, T., Hilgert, O., Aittakumpu-Hyden,
R., & Forman-Hoffman, V. (2021). A therapist-guided smartphone app for
major depression in young adults: a randomized clinical trial. *Journal
of Affective Disorders*, *286*, 228-238.

[Download
article](https://www.sciencedirect.com/science/article/pii/S0165032721001178)
